// test/adapter-no-volatile-content.test.js
//
// Plan 06-01 Task 3 — Pitfall 3 enforcement (06-RESEARCH.md):
// the renderer MUST NOT bake any volatile data into derived files
// (timestamps, suite VERSION, absolute paths, locale-dependent text).
// Otherwise every CI run produces churn for nothing.

import { strict as assert } from 'node:assert';
import { cp, mkdir, mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';

import { assembleAdapter } from '../scripts/assemble-adapter.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');

async function buildWorkspace() {
  const dir = await mkdtemp(path.join(tmpdir(), 'testatlas-volatile-'));
  await mkdir(path.join(dir, '.testatlas', 'schemas'), { recursive: true });
  await mkdir(path.join(dir, '.testatlas', 'commands'), { recursive: true });
  await mkdir(path.join(dir, '.testatlas', 'adapters'), { recursive: true });
  await cp(path.join(repoRoot, '.testatlas', 'schemas'), path.join(dir, '.testatlas', 'schemas'), {
    recursive: true,
  });
  await cp(
    path.join(repoRoot, '.testatlas', 'commands'),
    path.join(dir, '.testatlas', 'commands'),
    { recursive: true },
  );
  await cp(
    path.join(repoRoot, '.testatlas', 'adapters', 'adapter-capabilities.json'),
    path.join(dir, '.testatlas', 'adapters', 'adapter-capabilities.json'),
  );
  return dir;
}

async function snapshotTree(workspace) {
  const derivedDir = path.join(
    workspace,
    '.testatlas',
    'adapters',
    'claude-code',
    '.claude',
    'commands',
  );
  const { readdir } = await import('node:fs/promises');
  // V2 (Phase 14 Wave 5): the derived tree now contains category subdirs
  // (core/, explore/, council/, ...) so we walk recursively, keying each
  // entry by its path relative to derivedDir.
  const result = {};
  await walkInto(derivedDir, '', result);
  return result;

  async function walkInto(absDir, relPrefix, acc) {
    const entries = await readdir(absDir, { withFileTypes: true });
    for (const e of entries.sort((a, b) => a.name.localeCompare(b.name))) {
      const abs = path.join(absDir, e.name);
      const rel = relPrefix ? path.join(relPrefix, e.name) : e.name;
      if (e.isDirectory()) {
        await walkInto(abs, rel, acc);
      } else if (e.isFile()) {
        acc[rel] = await readFile(abs, 'utf8');
      }
    }
  }
}

test('Test 7: TESTATLAS_VERSION env change does not alter output', async () => {
  const wsA = await buildWorkspace();
  const wsB = await buildWorkspace();
  const origVersion = process.env.TESTATLAS_VERSION;
  try {
    process.env.TESTATLAS_VERSION = '1.0.0';
    await assembleAdapter({ adapter: 'claude-code', workspace: wsA });
    process.env.TESTATLAS_VERSION = '2.5.7';
    await assembleAdapter({ adapter: 'claude-code', workspace: wsB });

    const a = await snapshotTree(wsA);
    const b = await snapshotTree(wsB);

    for (const name of Object.keys(a)) {
      assert.equal(a[name], b[name], `${name} differs across TESTATLAS_VERSION values`);
    }
  } finally {
    if (origVersion === undefined) delete process.env.TESTATLAS_VERSION;
    else process.env.TESTATLAS_VERSION = origVersion;
    await rm(wsA, { recursive: true, force: true });
    await rm(wsB, { recursive: true, force: true });
  }
});

test('Test 8: derived files contain no ISO-8601 timestamps or version strings', async () => {
  const ws = await buildWorkspace();
  try {
    await assembleAdapter({ adapter: 'claude-code', workspace: ws });
    const tree = await snapshotTree(ws);
    // ISO-8601 datetime: 2026-05-03T12:00:00Z (or similar with offsets).
    const isoRe = /\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/;
    // Suite-version banner like "Generated by TestAtlas v1.0.0".
    const versionBanner = /Generated by TestAtlas v\d+\.\d+\.\d+/;

    for (const [name, text] of Object.entries(tree)) {
      // The marker envelope itself contains a hash, not a timestamp.
      assert.ok(!isoRe.test(text), `${name}: contains ISO-8601-looking timestamp`);
      assert.ok(!versionBanner.test(text), `${name}: contains version banner`);
    }
  } finally {
    await rm(ws, { recursive: true, force: true });
  }
});

test('Test 8b: rendering twice in succession produces byte-identical output', async () => {
  const ws = await buildWorkspace();
  try {
    await assembleAdapter({ adapter: 'claude-code', workspace: ws });
    const before = await snapshotTree(ws);
    // Re-run; second run is a no-op (idempotent), but compare anyway.
    await assembleAdapter({ adapter: 'claude-code', workspace: ws });
    const after = await snapshotTree(ws);

    for (const name of Object.keys(before)) {
      assert.equal(before[name], after[name], `${name}: not byte-identical between runs`);
    }
  } finally {
    await rm(ws, { recursive: true, force: true });
  }
});
